run:
  # We don't use generics so we can enable all the linters that don't work with Go 1.18.
  go: '1.17'

linters-settings:
  dupl:
    threshold: 100
  exhaustive:
    default-signifies-exhaustive: true
  funlen:
    lines: 100
    statements: 50
  goconst:
    min-len: 2
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  gocyclo:
    min-complexity: 15
  goimports:
    local-prefixes: github.com/kylrth/gpublame
  gomnd:
    settings:
      mnd:
        # don't include the "operation" and "assign"
        checks: argument,case,condition,return
  govet:
    check-shadowing: true
    enable-all: true
  lll:
    line-length: 100
  misspell:
    locale: US
  nolintlint:
    allow-unused: false
    allow-leading-space: false
    require-explanation: true
    require-specific: true

issues:
  exclude-rules:
    # no gomnd on test files
    - path: _test\.go
      linters:
        - gomnd

linters:
  disable-all: true
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - cyclop
    - deadcode
    - decorder
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - exportloopref
    - forcetypeassert
    - funlen
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - gofmt
    - gofumpt
    - goimports
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - grouper
    - govet
    - ifshort
    - importas
    - ineffassign
    - ireturn
    - lll
    - maintidx
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - paralleltest
    - prealloc
    - predeclared
    - promlinter
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - structcheck
    - stylecheck
    - tagliatelle
    - tenv
    - testpackage
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - wastedassign
    - whitespace
    - wsl
  # not enabled:
  # - exhaustivestruct  # This doesn't make sense to check for in most cases.
  # - forbidigo  # nothing to forbid
  # - gci  # prefer goimports
  # - gochecknoglobals  # I don't think globals should be universally disallowed.
  # - gochecknoinits  # I don't think init should be universally disallowed.
  # - goerr113  # I think it's ok to include info in errors without defining a new type.
  # - goheader  # no need for a header
  # - golint  # deprecated
  # - gomnd  # prefer goconst
  # - interfacer  # deprecated
  # - maligned  # deprecated
  # - scopelint  # deprecated
  # - varnamelen  # I don't think this matters.
  # - wrapcheck  # I think this should only happen for public functions.
